### GET request to example server
POST http://localhost:4000/api/review
Content-Type: application/json

{
  "movieId": 1,
  "content": "이 영화 재밌네요!!",
  "rating" : 3
}

###
@movieId=2
@page=0
@pageSize=10
@minRating=ab
GET http://localhost:4000/api/review/movie/{{movieId}}?page={{page}}&pageSize={{pageSize}}&minRating={{minRating}}
Content-Type: application/json

###
GET localhost:4000/api/review/1
