### GET request to example server
@page = -1
@pageSize = 10
GET localhost:4000/api/movie?page={{page}}&pageSize={{pageSize}}

###
@movieId = 8
GET localhost:4000/api/movie/{{movieId}}

###
POST localhost:4000/api/movie
Content-Type: application/json

{
  "title": "",
  "genre": "ACTION"
}

###
DELETE localhost:4000/api/movie
Content-Type: application/json

{
  "movieId": 1
}